export const SAVE_CATEGORIES = 'SAVE_CATEGORIES'

export const TOGGLE_CATEGORY_LOADING = 'TOGGLE_CATEGORY_LOADING'

export const SAVE_CATEGORIES_MSG = 'SAVE_CATEGORIES_MSG'

export const TOGGLE_EVENT_LOADING = 'TOGGLE_EVENT_LOADING'

export const SAVE_LATEST_EVENTS = 'SAVE_LATEST_EVENTS'

export const SAVE_EVENT_MSG = 'SAVE_EVENT_MSG'

export const SAVE_SINGLE_EVENTS = 'SAVE_EVENT_MSG'

export const SAVE_PAGINATED_EVENTS = 'SAVE_PAGINATED_EVENTS'

 

